"""Каталог треков и строки интерфейса (данные в коде: списки и словари)."""

# audio — путь относительно static/ (файлы в static/audio/)
TRACKS = [
    {
        "id": "t1",
        "title": "Dance Monkey",
        "artist": "Tones and I",
        "duration_min": 4,
        "genre": "pop",
        "audio": "audio/tones_dance_monkey.mp3",
    },
    {
        "id": "t2",
        "title": "Помнишь объятия на кухне",
        "artist": "Велосипед до Токио",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/velosiped_pomnish.mp3",
    },
    {
        "id": "t3",
        "title": "KAK MOMMY",
        "artist": "INSTASAMKA",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/instasamka_kak_mommy.mp3",
    },
    {
        "id": "t4",
        "title": "Ворона",
        "artist": "Kjenni MS, Дымка",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/kjenni_vorona.mp3",
    },
    {
        "id": "t5",
        "title": "Кукла колдуна",
        "artist": "Король и Шут",
        "duration_min": 4,
        "genre": "rock",
        "audio": "audio/kish_kukla.mp3",
    },
    {
        "id": "t6",
        "title": "Сыпь, гармоника",
        "artist": "SDP",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/sdp_syp_garmonika.mp3",
    },
    {
        "id": "t7",
        "title": "Пьяный туман",
        "artist": "GAYAZOV BROTHER",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/gayazov_pyany_tuman.mp3",
    },
    {
        "id": "t8",
        "title": "Лесник",
        "artist": "Король и Шут",
        "duration_min": 4,
        "genre": "rock",
        "audio": "audio/kish_lesnik.mp3",
    },
    {
        "id": "t9",
        "title": "Девочка, танцуй",
        "artist": "Artik & Asti",
        "duration_min": 3,
        "genre": "pop",
        "audio": "audio/artik_asti_devochka.mp3",
    },
]

TRACK_BY_ID = {t["id"]: t for t in TRACKS}

GENRES = [
    {"code": "pop", "label_ru": "Поп", "label_en": "Pop"},
    {"code": "rock", "label_ru": "Рок", "label_en": "Rock"},
]

UI = {
    "ru": {
        "brand": "Playlist Hub",
        "header_active_playlist": "Запущен плейлист:",
        "tagline": "Собирайте плейлисты из каталога — быстро и наглядно.",
        "nav_home": "Главная",
        "nav_catalog": "Каталог",
        "nav_create": "Создать плейлист",
        "nav_mine": "Мои плейлисты",
        "hero_title": "Музыка под настроение",
        "hero_text": (
            "Выберите треки из демо-каталога, задайте название — "
            "плейлист сохранится в вашей сессии браузера."
        ),
        "hero_art_aria": "Перейти в каталог треков",
        "catalog_title": "Каталог треков",
        "col_num": "#",
        "col_track": "Трек",
        "col_artist": "Исполнитель",
        "col_genre": "Жанр",
        "col_min": "Мин.",
        "col_play": "Прослушать",
        "create_title": "Новый плейлист",
        "create_name": "Название",
        "create_desc": "Описание (необязательно)",
        "create_tracks": "Треки",
        "create_submit": "Сохранить",
        "mine_title": "Мои плейлисты",
        "mine_empty": "Пока пусто — создайте первый плейлист.",
        "open": "Открыть",
        "tracks_count": "треков",
        "prefs_title": "Настройки (cookies)",
        "pref_theme": "Тема",
        "pref_lang": "Язык",
        "theme_light": "Светлая",
        "theme_dark": "Тёмная",
        "lang_ru": "Русский",
        "lang_en": "English",
        "visited_title": "Недавние страницы",
        "visited_playlist": "Плейлист",
        "footer_note": "Демо-проект: данные каталога заданы в коде.",
        "detail_tracks": "Состав",
        "playlist_player": "Воспроизведение плейлиста",
        "play_in_order": "Слушать по порядку",
        "back": "Назад к списку",
    },
    "en": {
        "brand": "Playlist Hub",
        "header_active_playlist": "Playlist on:",
        "tagline": "Build playlists from the catalog — quick and clear.",
        "nav_home": "Home",
        "nav_catalog": "Catalog",
        "nav_create": "Create playlist",
        "nav_mine": "My playlists",
        "hero_title": "Music for your mood",
        "hero_text": (
            "Pick tracks from the demo catalog, name your playlist — "
            "it is stored in your browser session."
        ),
        "hero_art_aria": "Open track catalog",
        "catalog_title": "Track catalog",
        "col_num": "#",
        "col_track": "Track",
        "col_artist": "Artist",
        "col_genre": "Genre",
        "col_min": "Min.",
        "col_play": "Listen",
        "create_title": "New playlist",
        "create_name": "Name",
        "create_desc": "Description (optional)",
        "create_tracks": "Tracks",
        "create_submit": "Save",
        "mine_title": "My playlists",
        "mine_empty": "Nothing here yet — create your first playlist.",
        "open": "Open",
        "tracks_count": "tracks",
        "prefs_title": "Settings (cookies)",
        "pref_theme": "Theme",
        "pref_lang": "Language",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "lang_ru": "Russian",
        "lang_en": "English",
        "visited_title": "Recent pages",
        "visited_playlist": "Playlist",
        "footer_note": "Demo project: catalog data is defined in code.",
        "detail_tracks": "Track list",
        "playlist_player": "Playlist playback",
        "play_in_order": "Play in order",
        "back": "Back to list",
    },
}
